version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.11
  build:
    commands:
      #- sam package --template-file user-migration-lambda/template.yml --s3-bucket s3-firebase-lambda-layer --output-template-file packaged-template.yml
      - cd user-migration-lambda && sam deploy --s3-bucket s3-firebase-lambda-layer
artifacts:
  files:
    - packaged-template.yml
