AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firebase-user-migration

  Firebase user migration lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  FirebaseUserMigrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        FirebaseUserMigration:
          Type: Api
          Properties:
            Path: /user-migration
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./firebase-user-migration
      Dockerfile: Dockerfile

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FirebaseUserMigrationApi:
    Description: API Gateway endpoint URL for Prod stage for Firebase User Migration function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FirebaseUserMigrationFunction:
    Description: Firebase User Migration Lambda Function ARN
    Value: !GetAtt FirebaseUserMigrationFunction.Arn
  FirebaseUserMigrationFunctionIamRole:
    Description: Implicit IAM Role created for Firebase User Migration function
    Value: !GetAtt FirebaseUserMigrationFunctionRole.Arn
